trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  webAppName: '<your-app-service-name>'  # Replace this
  packagePath: '$(Build.ArtifactStagingDirectory)/site.zip'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(packagePath)'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'static-site'
    publishLocation: 'Container'

# Deploy to Azure App Service using ZIP Deploy
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<your-service-connection-name>'  # e.g. AzureResourceManagerConnection
    appName: '$(webAppName)'
    package: '$(packagePath)'
